services:
  - type: web
    name: cattlenet-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        sync: false
      - key: MQTT_BROKER
        value: broker.emqx.io
      - key: MQTT_PORT
        value: 1883
      - key: CORS_ORIGINS
        value: "*"
      - key: ENABLE_SIMULATION
        value: False
