services:
  - type: web
    name: cattlenet-backend
    env: python
    buildCommand: chmod +x start.sh && pip install -r backend/requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        sync: false
      - key: MQTT_BROKER
        value: broker.emqx.io
      - key: MQTT_PORT
        value: 1883
      - key: CORS_ORIGINS
        value: "*"
      - key: ENABLE_SIMULATION
        value: False
